version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 8000:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      # - DRONE_ADMIN=foo # to turn on trusted environments
      - DRONE_HOST=http://<DRONE-HOSTNAME:PORT>
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://<GOGS-HOSTNAME:PORT>
      - DRONE_SECRET=INSERT_A_SECRET_STRING

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      # - DRONE_SERVER=wss://ci.example.com/ws/broker # for https hostnames
      - DRONE_SECRET=INSERT_A_SECRET_STRING
