version: '2'

services:
  drone-server:
    image: drone/drone:0.5
    ports:
      - 8000:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://<hostname>:3000
      - DRONE_SECRET=INSERT_A_SECRET_STRING

  drone-agent:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=INSERT_A_SECRET_STRING
